image: tmaier/docker-compose:latest

services:
    - docker:dind

before_script:
    - apt-get update && apt-get install -y git libzip-dev npm wget
    - apk add --no-cache docker-compose
    - docker version
    - docker-compose version

cache:
    paths:
        - vendor/

stages:
    - TestAPI

Newman:
    stage: TestAPI
    script:
        - docker-compose up -d
        - npm install -g newman
        - docker exec -i app-php bash
        - composer install
        - mv ./config/jwt/private_test.pem ./config/jwt/private.pem && mv ./config/jwt/public_test.pem ./config/jwt/public.pem
        - php bin/console doctrine:fixtures:load --no-interaction
        - newman run ./postman/postman_collection.json -e ./postman/postman_environment.json
    allow_failure: false