image: tmaier/docker-compose:latest

services:
    - docker:dind

before_script:
    - apt-get update && apt-get install -y php8-cli
    - docker-php-ext-install zip
    - curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
    - apk add --no-cache docker-compose
    - apk add --no-cache composer
    - php composer.phar
    - docker version
    - docker-compose version
    - docker-compose up -d
    - docker exec app-php bash

cache:
    paths:
        - vendor/

stages:
    - TestAPI

Newman:
    stage: TestAPI
    script:
        - apk update && apk add git libzip-dev npm wget
        - npm install -g newman
        - composer install
#        - mv ./config/jwt/private_test.pem ./config/jwt/private.pem && mv ./config/jwt/public_test.pem ./config/jwt/public.pem
#        - php bin/console doctrine:fixtures:load --no-interaction
#        - newman run ./postman/postman_collection.json -e ./postman/postman_environment.json
    allow_failure: false