image: php:8.0-cli

before_script:
    - apt-get update && apt-get install -y git libzip-dev npm wget
    - curl -sSk https://getcomposer.org/installer | php -- --disable-tls && mv composer.phar /usr/local/bin/composer
    - curl -L "https://github.com/docker/compose/releases/download/1.26.0/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
    - apt install apt-transport-https ca-certificates curl software-properties-common
    - apt-get install docker-engine -y
    - service docker start
    - docker -v
    - chmod +x /usr/local/bin/docker-compose
    - docker-compose version

cache:
    paths:
        - vendor/

stages:
    - TestAPI

Newman:
    stage: TestAPI
    script:
        - docker-compose up -d
        - npm install -g newman
        - composer install
        - mv ./config/jwt/private_test.pem ./config/jwt/private.pem && mv ./config/jwt/public_test.pem ./config/jwt/public.pem
        - php bin/console doctrine:fixtures:load --no-interaction
        - newman run ./postman/postman_collection.json -e ./postman/postman_environment.json
    allow_failure: false